# Generated by Django 5.2.11 on 2026-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_course_image_url_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
