# Generated by Django 5.2.11 on 2026-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_alter_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
