# Generated by Django 5.1.4 on 2026-02-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0005_alter_course_what_you_will_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('previous_qualification', models.CharField(max_length=100)),
                ('marks_percentage_cgpa', models.CharField(max_length=50)),
                ('passing_year', models.IntegerField()),
                ('school_college_name', models.CharField(max_length=255)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='enrollment/certificates/')),
                ('course_duration', models.CharField(max_length=100)),
                ('batch_timing', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('id_proof', models.FileField(upload_to='enrollment/id_proofs/')),
                ('passport_photo', models.ImageField(upload_to='enrollment/photos/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='enrollment/tc/')),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_contact', models.CharField(max_length=15)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='Courses.course')),
            ],
        ),
    ]
